### PR TITLE
Add .env.template file

### PR DESCRIPTION
**Pull request by muditmahajan21**
# Description

Added the .env.template file

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Added the file as well as the links

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KieranRobson** [comment]
Thanks @muditmahajan21!

**Comment by muditmahajan21** [comment]
> Thanks @muditmahajan21!

Cool! happy to contribute :))

**Comment by KieranRobson** [comment]
Feel free to contribute more if you need to for HF or just want to make the bot even better! Im happy to merge and grow Clarence!

**Comment by muditmahajan21** [comment]
> Feel free to contribute more if you need to for HF or just want to make the bot even better! Im happy to merge and grow Clarence!

I can add more similar commands (random facts from APIs or something like this), if you would like? Or if you have anything specific feature you would like?

**Comment by KieranRobson** [comment]
> I can add more similar commands (random facts from APIs or something like this), if you would like? Or if you have anything specific feature you would like?

Any new commands that you want to create, go ahead whether theyre cool API ones or just ones for a general discord server, or keep an eye out on the issues, as thats where ill put any new commands pd features!

**Comment by muditmahajan21** [comment]
> > I can add more similar commands (random facts from APIs or something like this), if you would like? Or if you have anything specific feature you would like?
> 
> Any new commands that you want to create, go ahead whether theyre cool API ones or just ones for a general discord server, or keep an eye out on the issues, as thats where ill put any new commands pd features!

Okay, I will search and add a couple of commands then. :)

**Pull request merged**
