### PR TITLE
add joke command

### PR DESCRIPTION
**Pull request by muditmahajan21**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Added a /joke and -joke command which calls the Joke API (https://v2.jokeapi.dev/) and outputs a random joke fetched from the API.

Fixes # (35)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

-Hosted the bot and invited to a personal server.
-Tested thoroughly and added exception handling.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by muditmahajan21** [comment]
@KieranRobson I have added both normal and slash commands, do you want to keep that as it is or remove the normal command? 
Also, I couldn't find any test as mentioned in the PR format?

**Comment by KieranRobson** [comment]
> @KieranRobson I have added both normal and slash commands, do you want to keep that as it is or remove the normal command? 
> Also, I couldn't find any test as mentioned in the PR format? 

I need to edit the template, could you run `npm run ci`, this will fix any issues with styling

**Comment by muditmahajan21** [comment]
> I need to edit the template, could you run `npm run ci`, this will fix any issues with styling

Ran  `npm run ci`, no files changed.

**Comment by muditmahajan21** [comment]
@KieranRobson Also, I noticed there is no `.env.template` file as mentioned in the README. I think it got deleted in a previous PR. I can add the file if you want.

**Comment by KieranRobson** [comment]
Awesome, I will merge this now @muditmahajan21, thanks!

**Comment by KieranRobson** [comment]
> @KieranRobson Also, I noticed there is no `.env.template` file as mentioned in the README. I think it got deleted in a previous PR. I can add the file if you want.

Just saw this @muditmahajan21, this would be great!

**Comment by muditmahajan21** [comment]
> Awesome, I will merge this now @muditmahajan21, thanks!

Thanks!

**Comment by muditmahajan21** [comment]
> > @KieranRobson Also, I noticed there is no `.env.template` file as mentioned in the README. I think it got deleted in a previous PR. I can add the file if you want.
> 
> Just saw this @muditmahajan21, this would be great!

Add the .env.template to this PR only or create a new one?

**Comment by KieranRobson** [comment]
A I merged this one before seeing the comment, a new pr would be needed, or I could just add it! Up to you!

**Comment by muditmahajan21** [comment]
> A I merged this one before seeing the comment, a new pr would be needed, or I could just add it! Up to you!

I have already created the file, let me push

**Pull request merged**
