### PR TITLE
added numberfact command

### PR DESCRIPTION
**Pull request by CH1NRU5T**
- Added the numberfact command
- Used the numbers api to fetch the fact
- Added the axios http library to the project to interact with the web and for making api calls.

### CODE REVIEW

**Comment by KieranRobson** [comment]
Thanks @CH1NRU5T! Although normal commands would work, Discord prefers Slash commands, is there any chance you could convert it to a slash command? 

No worries if not, happy to merge and add it to myself!

**Comment by CH1NRU5T** [comment]
Sorry, I don't know how to achieve that :(

**Comment by KieranRobson** [comment]
No worries at all! Ill merge and add it then if youd like you can see the small differences between them!

Thanks a ton! @CH1NRU5T

**Comment by CH1NRU5T** [comment]
Sure, will see the differences and get to learn it, thank you so much :)

**Comment by KieranRobson** [comment]
@CH1NRU5T So it turns out this command just lists ping? Is this correct?

Also the url is not defined within the command so this command would fail, I may have to revert unless you want to make a fix?

**Comment by CH1NRU5T** [comment]
It was working in my local machine.
I will check it first thing in the morning.
Will make the fix, don't worry

**Comment by CH1NRU5T** [comment]
I kept the embed template as it was, orange, gives ping and shows the uptime, do I have to modify it?

**Comment by KieranRobson** [comment]
Feel free to set the title as `'Number Fact'` and the description as `response.data` then you can get rid of the Add field

**Comment by CH1NRU5T** [comment]
- Solved the issue
- The new embed looks like this
image
it this okay?

**Pull request merged**
