### PR TITLE
Added Toggleable XP system

### LINKED ISSUE #7: Toggleable XP System

### PR DESCRIPTION
**Pull request by BranicekL**
# Description

I have added XP system, which is also toggleable. You can view information about users 
progress and his level, leaderboard and you can toggle this xp system on/off. 

XP off screen
xp on screen
xpOff
xpOn

Fixes #7

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I tested it manually, i have connected Clarence-Bot to my Discord server and ran the new commands which I have added to 
add new functionality.  

I tested it with command "/rank user: [here you add username]", which shows users rank on a simple rank card.  
Then viewed new added leaderboard with its command "/leaderboard", 
and then I have tested to toggle it on/off with command "/xpsystem on [True/False]". 
All the tests were seccessful.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have restored `.env.template`
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes - Run `npm run format`
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KieranRobson** [comment]
Hi @BranicekL! 

Huge thanks for this, 

I see you have `const Levels = require('discord-xp');` however discord-xp hasnt been added to the package json as a dependency. Should this be added? or am I missing something?

**Comment by BranicekL** [comment]
Ok I will add it shortly :)

**Comment by KieranRobson** [comment]
@BranicekL Thanks for the changes, could run `npm run format` to fix the linting issues?

**Comment by KieranRobson** [comment]
Ill merge and debug!

**Pull request merged**
